### PR TITLE
04012024 -- created skeleton for OMS frontEnd;

### PR DESCRIPTION
**Pull request by hellocarla**
-- created components and services for virus;
-- created components and services for areas;
-- created components and services for outbreaks;
-- created components and services for recommendations;
-- integrated CRUD operations for all components;
-- updated basic visuals.

### CODE REVIEW

**Review by riiiasg — APPROVED** [review]
ok

**Review by riiiasg — APPROVED** [review]
ok

**Review by inesdjfernandes — APPROVED** [review]
ok

**Review by inesdjfernandes — APPROVED** [review]
ok

**Review by riiiasg — APPROVED** [review]
ok

**Review by inesdjfernandes — APPROVED** [review]
ok

**Review by inesdjfernandes — APPROVED** [review]
ok

**Review by inesdjfernandes — APPROVED** [review]
ok

**Review by inesdjfernandes — APPROVED** [review]
ok

**Review by riiiasg — APPROVED** [review]
k

**Pull request closed without merging**
